"""add password salt

Revision ID: ee76d1dc93da
Revises: 3013fb661217
Create Date: 2024-07-15 23:45:55.794671

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee76d1dc93da'
down_revision: Union[str, None] = '3013fb661217'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin', sa.Column('password_salt', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admin', 'password_salt')
    # ### end Alembic commands ###
